# Generated by Django 6.0.3 on 2026-04-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('amount', models.FloatField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
